import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Providers } from "./Providers";

const bangers = Bangers({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={bangers.className}>
      <body className="bg-zinc-700 text-zinc-50">
        <div className="h-screen flex flex-col">
          <div className="flex flex-1">
            <Sidebar></Sidebar>
            <div className="w-full">
              {children}
            </div>
          </div>

          {/* <Footer></Footer> */}
        </div>
      </body>
    </html>
  );
}
